TOOLS_ROOT: /usr/lpp/rsusr/ported

# path leading to binaries that may be needed example: /hsstools/bin
TOOLS_PATH: '{{TOOLS_ROOT}}/bin'

system_environment:
  MANPATH: /usr/man/%L
  FFI_LIB: /usr/lpp/rsusr/python27/python-2017-04-12-py27/python27/lib/ffi
  RELEASE_NAME: python-2017-04-12
  CURL_CA_BUNDLE: /usr/lpp/rsusr/python27/python-2017-04-12-py27/python27/etc/ssl/cacert.pem
  RELEASE_DIR: /usr/lpp/rsusr/python27/python-2017-04-12-py27
  RELEASE_TYPE: py27
  LIBPATH: /usr/lpp/rsusr/python27/python-2017-04-12-py27/python27/lib:/lib:/usr/lib:.
  NLSPATH: /usr/lib/nls/msg/%L/%N
  PATH: /usr/lpp/rsusr/python27/python-2017-04-12-py27/python27/bin:/bin:.
  MAIL: /usr/mail/OMVSADM
  _: /bin/env
  TERMINFO: /usr/lpp/rsusr/python27/python-2017-04-12-py27/python27/share/terminfo
  PYTHON_ENV: python27
  PKG_CONFIG_PATH: /usr/lpp/rsusr/python27/python-2017-04-12-py27/python27/lib/pkgconfig:/usr/lpp/rsusr/python27/python-2017-04-12-py27/python27/share/pkgconfig
  PYTHON_HOME: /usr/lpp/rsusr/python27/python-2017-04-12-py27/python27
  _BPXK_JOBLOG: STDERR 
  _BPXK_AUTOCVT: ON
  _CEE_RUNOPTS: 'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'
  _TAG_REDIR_ERR: txt
  _TAG_REDIR_IN: txt
  _TAG_REDIR_OUT: txt
  TOOLS_ROOT: '{{ TOOLS_ROOT }}'
  GIT_SHELL=: '{{ TOOLS_ROOT }}/bin/bash'
  GIT_EXEC_PATH: '{{ TOOLS_ROOT }}/libexec/git-core'
  GIT_TEMPLATE_DIR: '{{ TOOLS_ROOT }}/share/git-core/templates'
  # Java environment
  JAVA_HOME: /usr/lpp/java/java180/J8.0_64


vars_folder_name: vars_zvm

# Config members shared across multiple playbooks 

# The job card to be use for any batch jobs run
# Ensure that the job logs will be accessible with provided configuration
JOB_CARD: |- 
  //ANSIBLE JOB 'testing',
  //  NOTIFY={{ TARGET_USERNAME | upper }},
  //  USER={{ TARGET_USERNAME | upper }},
  //  MSGCLASS=E,
  //  MSGLEVEL=(1,1),
  //  CLASS=A

# The username that will be used to establish SSH connection to target 
TARGET_USERNAME: omvsadm

# Where to install MVSUTILS/MVSCMD and other needed tools/scripts
uss_utilities_path: /u/{{ TARGET_USERNAME }}

# Where generated JCL files should be saved on target
uss_file_path: /u/{{ TARGET_USERNAME }}

# Enable to reserve ports for ICON at runtime, will overwrite the PORTID values provided below
# This feature is experimental
dynamic_port_reservation: no

# Port information to be used for IMS Connect
DFS_PORTID: 9978
DFS_SSLPORTID: 9979
DFS_REGION_TCPIPPORT: 9977
DFS_REGION_SSLTCPIPPORT: 9966
# location of system tcpip profile
TCPIP_PROFILE: USER.PARMLIB(TCPPROF2)
# location to store our altered tcpip profile
TCPIP_PROFILE_TMP: '{{ DFS_AUTH_LIB_HLQ1 }}.TEMP(imsprof)'

DFS_IMS_USERID: '{{ TARGET_USERNAME | upper }}'

DFS_IMS_SSID: IMS1

DFS_AUTH_LIB_HLQ1: IMSBANK        

DFS_AUTH_LIB_HLQ2: '{{ DFS_IMS_SSID }}' 

DFS_AUTH_LIB_SYSHLQ1: IMSBLD

DFS_AUTH_LIB_SYSHLQ2: I15RTSMM

DFS_JOBLIB: '{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.JOBS'

DFS_RESLIB: '{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.SDFSRESL'

DFS_PROCLIB: '{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB'

DFS_SMS_ENVIRONMENT: false
DFS_SMS_CLASS: CLASS2
DFS_SMS_MCLASS: NONE

DFS_DS_VOLUME1: W68001
DFS_DS_VOLUME2: W68002

JAVA_CONF_PATH: /u/dfsjvmpr.props
DFS_workingdir: /u/{{ TARGET_USERNAME }}


DFS_IMSPlex: PLEX1

zCloud_LERuntime: CEE.SCEERUN

zCloud_MACLIB: SYS1.MACLIB

zCloud_CSSLIB: SYS1.CSSLIB

